name: LeetCode Auto Sync

on:
  schedule:
    - cron: '0 2 * * 0'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt

      - name: Run sync CLI
        env:
          LC_SESSION: ${{ secrets.LC_SESSION }}
          LC_CSRF: ${{ secrets.LC_CSRF }}
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
          GH_OWNER: ${{ secrets.GH_OWNER }}
          GH_REPO: ${{ secrets.GH_REPO }}
        run: python sync.py sync


